### ISSUE TITLE
Get UC_ERR_WRITE_UNMAPPED when push registers into the stack.

### ISSUE THREAD

**Issue by iven00000000** [hugsy/cemu#37] opened 2018-09-14 14:06 UTC
OS: Windows 10
Target Architecture: ARM Native mode
Codes:
`push {r0}`
Logs:

> Switching to 'ARM Native mode'
[logger] Setup - Map .text @40000 (size=4096,perm=READ|EXEC)
[logger] Setup - Map .data @60000 (size=4096,perm=READ|WRITE)
[logger] Setup - Map .stack @800000 (size=16384,perm=READ|WRITE)
[logger] Setup - Map .misc @900000 (size=4096,perm=ALL)
[logger] Compilation - Assembling 1 instructions for ARM Native mode:b'push {r0}'
[logger] Compilation - 1 instruction(s) compiled: 4 bytes
[logger] Setup - Register 'R0' = 0x0
[logger] Setup - Register 'R1' = 0x0
[logger] Setup - Register 'R2' = 0x0
[logger] Setup - Register 'R3' = 0x0
[logger] Setup - Register 'R4' = 0x0
[logger] Setup - Register 'R5' = 0x0
[logger] Setup - Register 'R6' = 0xffff0ff0
[logger] Setup - Register 'R7' = 0x400
[logger] Setup - Register 'R8' = 0x0
[logger] Setup - Register 'R9' = 0x0
[logger] Setup - Register 'R10' = 0x0
[logger] Setup - Register 'R12' = 0x0
[logger] Setup - Register 'FP' = 0x0
[logger] Setup - Register 'LR' = 0x0
[logger] Setup - Register 'CPSR' = 0x0
[logger] Setup - Register 'PC' = 0x0
[logger] Setup - Register 'SP' = 0x0
[logger] Setup - Mapping .text at 0x40000
[logger] Runtime - Executing instruction at 0x40000
[logger] Error - An error occured: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

**Comment by hugsy** [comment] 2019-01-24 02:21
Not a bug, closing.

You are attempting to push to an area unallocated. This error is the normal behavior. Move your stack pointer inside an allocated region and you'll be fine.

**Closed by hugsy** 2019-01-24 02:21 UTC
