### ISSUE TITLE
Text is white on windows.

### ISSUE THREAD

**Issue by abnormalhare** [hugsy/cemu#95] opened 2024-07-22 00:14 UTC
* [X] Did you use the latest version of CEMU from `dev` branch?
* [X] Did you check [current and past issues](https://github.com/hugsy/cemu/issues)?
* [X] Did you check [current and past PR](https://github.com/hugsy/cemu/pulls)?

### Step 1: Describe your environment

* Operating System / Distribution: Windows 11 64-bit
* Python version: 3.12
* CEMU version (installed from `pip`, `git` etc.): 0.8

### Step 2: Describe your problem
Text is not visible due to it being white on a white background. Also, the color for highlighting is purple, and when not selected, is black.

#### Steps to reproduce

1. Run the emulator on Windows
2. Use any textbox

#### Observed Results

* What happened? This could be a description, log output, etc.

#### Expected results

* What did you expect to happen?
I expected the UI to look similar to the one on Linux

#### Traces

![image](https://github.com/user-attachments/assets/c57508af-1868-43ec-8bea-8d9679eb812d)

**Comment by hugsy** [comment] 2024-07-23 16:29
Thanks for your detailed issue.

However I cannot reproduce:

![image](https://github.com/user-attachments/assets/ca2ca38a-2ac7-454c-ac58-fe90dc77a964)

I'm not sure if it's related, but are you using dark mode on windows? Try toggle it and let me know.

**Comment by abnormalhare** [comment] 2024-07-25 12:25
I'd very much prefer to not do so, is it possible for the application to account for that?

**Comment by hugsy** [comment] 2024-07-25 16:16
> I'd very much prefer to not do so, is it possible for the application to account for that?

It was a suggestion, but I did try on dark and light mode, the text shows perfectly. So I still cannot reproduce your problem.

**Comment by hugsy** [comment] 2024-07-29 21:16
FWIW this "might" be fixed by #96

**Comment by hugsy** [comment] 2024-07-30 16:29
@abnormalhare #96 was merged, feel free to try again by building from the `main` branch. If it still doesn't work try to isolate the reason, since (like shown above) I cannot reproduce your case (tested on 10 & 11)

**Comment by abnormalhare** [comment] 2024-08-01 18:08
thank you! sorry i havent been following this, got a bit busy

**Comment by hugsy** [comment] 2024-08-02 19:50
> thank you! sorry i havent been following this, got a bit busy

no problem, you can close the issue if it's fixed 😄

**Closed** 2024-08-10 15:47 UTC
